### ISSUE TITLE
-eオプションと-Fオプションを併用すると、斜体フォントが生成されない。

### ISSUE THREAD

**Issue by azarashichop** [omonomo/Cyroit#7]
そもそも可能なのか、というところもありますが`./run_ff_ttx.sh -e -F`とすると　　
Cyroitルートディレクトリにフォントが生成されます。  
フォントはRegularとBoldの2種類しか生成されません。

仕様なのか含め、ご確認お願いします。

**Comment by omonomo** [comment]
回答が遅くなりまして申しわけございません。
run_ff_ttx.sh はオプションの併用が出来ません。
ご面倒をおかけしますが、run_ff_ttx.sh で呼び出している font_generator.sh の
オプションを変更して実行してみてください。

よろしくお願いいたします。

**Comment by omonomo** [comment]
回答が遅くなりまして申しわけございません。
run_ff_ttx.sh はオプションの併用が出来ません。
ご面倒をおかけしますが、run_ff_ttx.sh を編集していただき、
スクリプト内で呼び出している font_generator.sh の
オプションを変更して実行してみてください。

よろしくお願いいたします。

**Comment by omonomo** [comment]
README.md に生成スクリプトの説明をもう少し詳しく記述しました。

**Comment by azarashichop** [comment]
ご確認、READMEの更新ありがとうございます。内容理解いたしました。
